INSERT INTO distilleries (distillery, website, city)
VALUES ("10TH MOUNTAIN WHISKEY & SPIRIT COMPANY", "http://10thwhiskey.com", "Vail"),
("1350 DISTILLING", "http://1350distilling.com", "Colorado Springs"),
("3 HUNDRED DAYS DISTILLING","http://www.3hundreddays.com","Monument"),
("52EIGHTY DISTILLING","http://52eightydistilling.com","Littleton"),
("ARCHETYPE DISTILLERY","http://www.archetypedistilling.com","Denver"),
("AXE AND THE OAK WHISKEY HOUSE","http://www.axeandtheoak.com","Colorado Springs"),
("BEAR CREEK DISTILLERY","http://www.bearcreekdistillery.com","Denver"),
("BIG FAT PASTOR SPIRITS","http://bigfatpastorspirits.com","Loveland"),
("BLACK BEAR DISTILLERY","http://www.blackbeardistillery.com","Green Mountain Falls"),
("BOUCK BROTHERS DISTILLING","http://www.bouckbros.com","Idaho Springs"),
("BRECKENRIDGE DISTILLERY","http://breckenridgedistillery.com","Breckenridge"),
("BRANCH & BARREL WHISKEY","http:/www.branchandbarrelwhiskey.com","Centennial"),
("COLORADO GOLD DISTILLERY","http://ColoradoHighVodka.com","Colorado Springs"),
("COPPERMUSE DISTILLERY","http://www.coppermuse.com","Fort Collins"),
("DEERHAMMER DISTILLING COMPANY","http://deerhammer.com","Buena Vista"),
("DENVER DISTILLERY","http://Denverdistillery.com","Denver"),
("DEVIANT SPIRIT DV8","http://deviantspirits.com","Boulder"),
("DEVIATION DISTILLING","http://www.deviationdistilling.com","Denver"),
("DEVIL'S HEAD DISTILLERY","http://www.devilsheaddistillery.com","Englewood"),
("DISTILLERY 291","http://www.distillery291.com","Colorado Springs"),
("DOWNSLOPE DISTILLING","http://www.downslopedistilling.com","Centennial"),
("DRY LAND DISTILLERS","https://drylanddistillers.com","Longmont"),
("DURANGO CRAFT SPIRITS","http://www.durangospirits.com","Durango"),
("ELEVATION 5003 DISTILLERY","http://www.elevation5003.com","Fort Collins"),
("ELKINS DISTILLING CO.","http://www.elkinsdistilling.com","Estes Park"),
("ELWOOD DISTILLING","http://www.elwooddistilling.com","Boulder"),
("FEISTY SPIRITS DISTILLERY","http://FeistySpirits.com","Fort Collins"),
("GOLDEN MOON DISTILLERY","http://www.goldenmoondistillery.com","Golden"),
("HONEY HOUSE DISTILLERY","http://www.honeyhousedistillery.com","Durango"),
("IDLEWILD SPIRITS DISTILLERY","http://www.idlewildspirits.com","Winter Park"),
("IRONTON DISTILLERY & CRAFTHOUSE","http://www.irontondistillery.com","Denver"),
("J&L DISTILLERY","http://www.jldistilling.com","Boulder"),
("K J WOOD DISTILLERS","http://www.kjwooddistillers.com","Ouray"),
("LAWS WHISKEY HOUSE","http://www.lawswhiskeyhouse.com","Denver"),
("LEE SPIRITS COMPANY","http://www.leespirits.com","Colorado Springs"),
("LEOPOLD BROS.","http://www.leopoldbros.com","Denver"),
("LONTUCKY SPIRITS","http://www.longtuckyspirits.com","Longmont"),
("MAD RABBIT DISTILLERY","http://madrabbitdistillery.com","Westminster"),
("MARBLE DISTILLING CO.","http://www.marbledistilling.com","Carbondale"),
("MILE HIGH SPIRITS","http://www.DrinkMHS.com","Denver"),
("MYSTIC MOUNTAIN DISTILLERY","http://www.mmdistillery.com","Thornton"),
("MYTHOLOGY DISTILLERY","http://www.mythologydistillery.com","Denver"),
("NOCO DISTILLERY","http://www.nocodistillery.com","Fort Collins"),
("OLD ELK DISTILLERY","http://www.olkelk.com","Fort Collins"),
("OLD TOWN DISTILLING CO.","http://www.oldtowndistilling.com","Fort Collins"),
("ON POINT DISTILLERY","http://www.12pointdistillery.com","Lafayette"),
("PEACH STREET DISTILLERS","http://www.peachstreetdistillers.com","Palisade"),
("RISING SUN DISTILLERY","http://www.risingsundistillery.com","Denver"),
("ROCKER SPIRITS","http://www.rockerspirits.com","Littleton"),
("SAND CREEK DISTILLERY","http://www.sandcreekdistillery.com","Hugo"),
("SANTA FE SPIRITS DISTILLERY","http://www.santafespirits.com","Santa Fe "),
("SPIRIT HOUND DISTILLERS","http://www.spirithounds.com","Lyons"),
("STATE 38 DISTILLING","http://www.state38.com","Golden"),
("STEAMBOAT WHISKEY COMPANY","http://www.steamboatwhiskeyco.com","Steamboat Springs"),
("STONEYARD DISTILLERY","http://stoneyarddistillery.com","Dotsero"),
("STORM KING DISTILLING CO.","http://www.stormkingdistilling.com","Montrose"),
("STRANAHAN'S COLORADO WHISKEY","http://www.stranahans.com","Denver"),
("SYNTAX DISTILLERY","http://www.syntaxspirits.com","Greeley"),
("TALNUA DISTILLERY","http://www.talnua.com","Arvada"),
("THE BLOCK DISTILLING CO.","http://www.theblockdistillingco.com","Denver"),
("THE FAMILY JONES","http://www.thefamilyjones.co","Denver"),
("THE HEART DISTILLERY","https://theheartdistillery.com","Windsor"),
("TOWER 56 DISTILLING","http://www.tower56.com","Greeley"),
("VAPOR DISTILLERY","http://www.vapordistillery.com","Boulder"),
("WHISTLING HARE DISTILLERY","http://www.whistlinghare.com","Westminster"),
("WOOD'S HIGH MOUNTAIN DISTILLERY","http://woodsdistillery.com","Salida"),
("WOODY CREEK DISTILLERS","http://www.woodycreekdistillers.com","Basalt");

INSERT INTO alcohol (name, alcoholType, flavor, DistilleryId)
VALUES ("10TH Mountain Bourbon","Bourbon","Woody-Nutty","1"),
("10TH Mountain Rye Whiskey","Whiskey","Caramel","1"),
("10TH Mountain Spirits Alpenglow Cordial","Liqueurs-Cordials","Fruity","1"),
("10TH Mountain Vodka","Vodka","None-Mild","1"),
("Western Sippin' Shine - Apple Pie","Moonshine","Fruity","3"),
("Western Sippin' Shine - Colorado Honey","Moonshine","Caramel","3"),
("Western Sippin' Shine - Firebomb","Moonshine","Herbal-Spice","3"),
("Western Sippin' Shine - Margarita Moon","Moonshine","Citrus","3"),
("Western Sippin' Shine - Sugar Moon","Moonshine","None-Mild","3"),
("Western Sippin' Shine - Rocky Mountain Sweet Tea","Moonshine","None-Mild","3"),
("Western Sippin' Shine - Summertime Strawberry Lemononde","Moonshine","Fruity","3"),
("Western Sippin' Shine - Peach Cobbler","Moonshine","Fruity","3"),
("American Small Batch Gin","Gin","Citrus","4"),
("Hearthstone Whiskey","Whiskey","Woody-Nutty","4"),
("Cackler's Whiskey","Whiskey","Caramel","4"),
("Summer Peach Vodka","Vodka","Fruity","4"),
("Winter Wheat Vodka","Vodka","Vanilla","4"),
("Archangel Vodka","Vodka","Citrus","5"),
("Archrival Gin","Gin","Herbal-Spice","5"),
("Pikes Peak Hill Shine","Moonshine","Herbal-Spice","6"),
("Colorado Mountain Bourbon Whiskey","Bourbon","Vanilla","6"),
("Colorado Mountain Incline Rye Whiskey","Whiskey","Caramel","6"),
("Straight Bourbon","Bourbon","Herbal-Spice","7"),
("Wheated Bourbon","Bourbon","Caramel","7"),
("Rye Whiskey","Whiskey","None-Mild","7"),
("Wheat Whiskey","Whiskey","None-Mild","7"),
("White Whiskey","Whiskey","None-Mild","7"),
("Rye Vodka","Vodka","None-Mild","7"),
("Wheat Vodka","Vodka","None-Mild","7"),
("Silver Rum","Rum","None-Mild","7"),
("Spiced Rum","Rum","Vanilla","7"),
("Cask Strength Rum","Rum","None-Mild","7"),
("Vodka","Vodka","Floral","8"),
("Genesis Gin","Gin","Floral","8"),
("Barrel Rested Genesis Gin","Gin","Vanilla","8"),
("Soul Searchin' Bourbon Whiskey","Bourbon","Caramel","8"),
("Holy Smokes Malt Whiskey","Whiskey","Woody-Nutty","8"),
("Black Bear Irish Style Whiskey","Whiskey","None-Mild","9"),
("Black Bear Gold Rum","Rum","None-Mild","9"),
("Black Bear White Rum","Rum","None-Mild","9"),
("MountainShine","Moonshine","None-Mild","9"),
("MountainShine Reserve","Moonshine","Woody-Nutty","9"),
("Black Bear Gold Rum","Rum","None-Mild","9"),
("Black Bear Vodka","Vodka","None-Mild","9"),
("Colorado Coffee Whiskey","Whiskey","None-Mild","10"),
("Pink Bear Gin","Gin","Herbal-Spice","10"),
("Brown Bear Gin","Gin","Vanilla","10"),
("Breckenridge Bourbon Whiskey","Bourbon","Vanilla","11"),
("Breckenridge Reserve Blend","Bourbon","None-Mild","11"),
("Breckenridge Whiskey Post Cask Finish","Bourbon","Caramel","11"),
("Breckenridge Whiskey PX Cask Finish","Whiskey","Vanilla","11"),
("Breckenridge Distillers High Proof","Whiskey","Caramel","11"),
("Breckenridge Dark Arts: Whiskey Distilled from Malt Mash","Whiskey","Caramel","11"),
("Breckenridge Bourbon Whiskey Single Barrel","Bourbon","Caramel","11"),
("Breckenridge Spiced Whiskey","Whiskey","Herbal-Spice","11"),
("Breckenridge Gin","Gin","Citrus","11"),
("Breckenridge Spiced Rum","Rum","Herbal-Spice","11"),
("Breckenridge Bitter","Other","Herbal-Spice","11"),
("Breckenridge Vodka","Vodka","Citrus","11"),
("Breckenridge Pear Flavored Vodka","Vodka","Fruity","11"),
("Breckenridge Chili Chile Vodka","Vodka","Herbal-Spice","11"),
("Breckenridge Espresso Flavored Vodka","Vodka","None-Mild","11"),
("Branch & Barrel White Oak","Whiskey","Caramel","12"),
("Branch & Barrel Honey Barrel Finished","Whiskey","Caramel","12"),
("Branch & Barrel Plum","Whiskey","Herbal-Spice","12"),
("Branch & Barrel Holiday Twist","Whiskey","Caramel","12"),
("Colorado High Hemp Vodka","Vodka","None-Mild","13"),
("Vertueux Vodka","Vodka","None-Mild","14"),
("Vicieux Black Vodka","Vodka","None-Mild","14"),
("Coppermuse Silver Rum","Rum","Vanilla","14"),
("Coppermuse Gold Rum","Rum","Vanilla","14"),
("Coppermuse Spiced Rum","Rum","Herbal-Spice","14"),
("Coppermuse Bacon Vodka","Vodka","Woody-Nutty","14"),
("Coppermuse Cucumber Vodka","Vodka","None-Mild","14"),
("Coppermuse Honey & Dill Vodka","Vodka","Honey","14"),
("Coppermuse Horseradish Vodka","Vodka","Herbal-Spice","14"),
("Coppermuse Jalapeno Vodka","Vodka","Herbal-Spice","14"),
("Coppermuse Lavendar Vodka","Vodka","Floral","14"),
("Coppermuse Amaretto Liqueur","Liqueurs-Cordials","Woody-Nutty","14"),
("Coppermuse Coffee Liqueur","Liqueurs-Cordials","Vanilla","14"),
("Coppermuse Whiskey","Whiskey","Woody-Nutty","14"),
("Coppermuse Gin with Hibiscus","Gin","Herbal-Spice","14"),
("Coppermuse Strawberry Vodka","Vodka","Fruity","14"),
("DeerHammer Straight Bourbon","Bourbon","Woody-Nutty","15"),
("DeerHammer Rough & Tumble","Whiskey","Woody-Nutty","15"),
("DeerHammer American Single Malt Whiskey","Whiskey","Caramel","15"),
("DeerHammer Dutch Style Gin","Gin","Herbal-Spice","15"),
("Denver Distillery Sweet Potato Vodka","Vodka","Caramel","16"),
("Denver Distillery Gin","Gin","Herbal-Spice","16"),
("Denver Distillery Dark Rum","Rum","Caramel","16"),
("Denver Distillery Silver Rum","Rum","Caramel","16"),
("Denver Distillery Navy Strength Spiced Rum","Rum","Caramel","16"),
("Denver Distillery Lemon Lime Sweet-Feed Shine","Moonshine","Citrus","16"),
("Denver Distillery Punkin' Head Liqueur","Liqueurs-Cordials","Fruity","16"),
("Denver Distillery Apple Pie Shine","Moonshine","Fruity","16"),
("Denver Distillery Coffee Liqueur","Liqueurs-Cordials","Caramel","16"),
("Denver Distillery Strawberry Kiwi Liqueur","Liqueurs-Cordials","Fruity","16"),
("DV8 Vodka","Vodka","Fruity","17"),
("DV8 Gin","Gin","Herbal-Spice","17"),
("DV8 Whiskey","Whiskey","Caramel","17"),
("Deviation Distilling Citrus Rose","Gin","Citrus","18"),
("Deviation Distilling Mountain Herb","Gin","Herbal-Spice","18"),
("Deviation Distilling Spice Trade","Gin","Herbal-Spice","18"),
("Oak Barrel Reserve Aquavit","Whiskey","None-Mild","19"),
("Aquavit","Whiskey","Herbal-Spice","19"),
("Gin","Gin","Floral","19"),
("Vodka","Vodka","None-Mild","19"),
("Barrel Proof Colorado Whiskey","Whiskey","Woody-Nutty","20"),
("Single Barrel Colorado Rye Whiskey","Whiskey","Herbal-Spice","20"),
("Single Barrel Colorado Bourbon Whiskey","Bourbon","Caramel","20"),
("Barrel Proof Colorado Bourbon Whiskey","Bourbon","Woody-Nutty","20"),
("Small Batch American Whiskey","Whiskey","Woody-Nutty","20"),
("Fresh Colorado Whiskey","Whiskey","None-Mild","20"),
("White Dog Colorado Rye Whiskey","Whiskey","None-Mild","20"),
("Bad Guy Colorado Bourbon Whiskey","Bourbon","Caramel","20"),
("High Rye Colorado Bourbon Whiskey","Bourbon","Vanilla","20"),
("The DECC Citrus Clove Liqueur","Liqueurs-Cordials","Fruity","20"),
("Double Diamond Whiskey","Whiskey","Woody-Nutty","21"),
("Limited Edition - Double Diamond 4 Year","Whiskey","Woody-Nutty","21"),
("Limited Edition - Rye","Whiskey","Woody-Nutty","21"),
("Vodka from Unrefined Cane","Vodka","Caramel","21"),
("Vodka from Malt and Rye","Vodka","None-Mild","21"),
("Pepper Vodka","Vodka","Herbal-Spice","21"),
("White Cane Rum","Rum","Vanilla","21"),
("Vanilla Rum","Rum","Vanilla","21"),
("Wine Barrel Aged Rum","Rum","None-Mild","21"),
("Agave Spirit","Tequila","None-Mild","21"),
("Downslope Ould Tom Gin","Gin","Herbal-Spice","21"),
("Dry Land Heirloom Wheat Whiskey","Whiskey","Vanilla","22"),
("Dry Land Colorado Antero Wheat Whiskey","Whiskey","Caramel","22"),
("Dry Land Cactus","Tequila","Woody-Nutty","22"),
("Dry Land Pure Cane Rum","Rum","None-Mild","22"),
("Dry Land Gin","Gin","None-Mild","22"),
("Soiled Doves Vodka","Vodka","None-Mild","23"),
("Mayday Moonshine","Moonshine","None-Mild","23"),
("Cinder Dick Bourbon Whiskey","Bourbon","None-Mild","23"),
("Straight Rye Whiskey","Whiskey","Vanilla","24"),
("Narrow Road Vodka","Vodka","Woody-Nutty","24"),
("Timber Ridge Gin","Gin","Citrus","24"),
("Lunarshine Corn Whiskey","Whiskey","Caramel","24"),
("Falernu Liqueur","Liqueurs-Cordials","Woody-Nutty","24"),
("Franklin Coffee Liqueur","Liqueurs-Cordials","Vanilla","24"),
("Elkins Distilling Co. Corn Whiskey","Whiskey","Woody-Nutty","25"),
("Elkins Colorado Whiskey","Whiskey","Woody-Nutty","25"),
("Elkins Apple Spiced Liqueur","Liqueurs-Cordials","Herbal-Spice","25"),
("Elwood Distilling Co. Single Malt Whiskey","Whiskey","Woody-Nutty","26"),
("Rockit Rye 100% Rye Whiskey","Whiskey","Caramel","27"),
("Rhapsody Blue Corn Bourbon","Bourbon","Caramel","27"),
("Better Days Bourbon","Bourbon","Woody-Nutty","27"),
("Wild Thing Colorado Whiskey","Whiskey","Woody-Nutty","27"),
("Better Days Bourbon","Bourbon","Caramel","27"),
("O'Feisty McBourbon","Bourbon","Herbal-Spice","27"),
("Red, White & Blue Bourbon","Bourbon","Caramel","27"),
("Maple and Cinnamon Whiskey","Whiskey","Caramel","27"),
("Cinnamon Oat","Whiskey","Herbal-Spice","27"),
("Blackberry","Whiskey","Fruity","27"),
("Vanilla Orange","Whiskey","Vanilla","27"),
("Apple Brandy","Brandy","Fruity","27"),
("Pear Brandy","Brandy","Fruity","27"),
("Peach Brandy","Brandy","Fruity","27"),
("Yellow Corn Oat Bourbon","Bourbon","Caramel","27"),
("Yellow Corn Oat Bourbon - Finished in a Peach Brandy Barrel","Bourbon","Fruity","27"),
("Red Corn Oat Bourbon","Bourbon","Caramel","27"),
("Golden Moon Gin","Gin","Herbal-Spice","28"),
("Port Cask Reserve Gin","Gin","None-Mild","28"),
("Golden Moon Colorado Single Malt Whiskey","Whiskey","Woody-Nutty","28"),
("Golden Moon Ex Gratia","Other","Herbal-Spice","28"),
("Golden Moon Kummel","Other","None-Mild","28"),
("Golden Moon Amer dit Picon","Other","Herbal-Spice","28"),
("Golden Moon Creme de Violette","Other","Floral","28"),
("REDUX Absinthe","Absinthe","Herbal-Spice","28"),
("Golden Moon Dry Curacao","Other","Citrus","28"),
("Apple Jack","Other","Fruity","28"),
("Gun Fighter American Bourbon - Double Cask","Bourbon","Woody-Nutty","28"),
("Gun Fighter American Rye - Double Cask","Whiskey","Woody-Nutty","28"),
("Colorado Honey Whiskey","Whiskey","Caramel","29"),
("Hex Vodka","Vodka","Caramel","29"),
("Cinnamon Honey Whiskey","Whiskey","Herbal-Spice","29"),
("Cold Brew Coffee Liqueur","Liqueurs-Cordials","Vanilla","29"),
("Red Cliffs Spiced Rum","Rum","Herbal-Spice","29"),
("Woodcutter's Bourbon Whiskey","Bourbon","Woody-Nutty","30"),
("Colorado Single Malt Whiskey","Whiskey","Caramel","30"),
("Barrel Aged Gin","Gin","Woody-Nutty","30"),
("Alpine Gin","Gin","Citrus","30"),
("Foragin'","Gin","Herbal-Spice","30"),
("Vanilla Vodka","Vodka","Vanilla","30"),
("Rocky Mountain Gold Rum","Rum","Caramel","30"),
("Hibiscus Infused Gin","Gin","Herbal-Spice","30"),
("Idlewild Vodka","Vodka","None-Mild","30"),
("Housemade Vodka","Vodka","None-Mild","31"),
("Genievre Gin","Gin","Herbal-Spice","31"),
("Ponderosa Gin","Gin","Woody-Nutty","31"),
("Rye Aquavit","Other","Herbal-Spice","31"),
("Platinum Rum","Rum","Caramel","31"),
("Ginger","Liqueurs-Cordials","Herbal-Spice","31"),
("Mint","Liqueurs-Cordials","Herbal-Spice","31"),
("Cacao","Liqueurs-Cordials","Caramel","31"),
("Coffee","Liqueurs-Cordials","Caramel","31"),
("Amaro","Liqueurs-Cordials","Herbal-Spice","31"),
("Orange","Liqueurs-Cordials","Citrus","31"),
("Amaretto","Liqueurs-Cordials","Caramel","31"),
("Pumpkin Spice","Liqueurs-Cordials","Herbal-Spice","31"),
("Papa's Bitters Herbal","Bitters-Schnapps","Herbal-Spice","31"),
("Papa's Bitters Walnut","Bitters-Schnapps","Woody-Nutty","31"),
("Papa's Bitters Citrus","Bitters-Schnapps","Citrus","31"),
("Papa's Bitters Cherry Basil","Bitters-Schnapps","Fruity","31"),
("Papa's Bitters Old Fashioned","Bitters-Schnapps","Woody-Nutty","31"),
("Smoked Single Malt Whiskey","Whiskey","Woody-Nutty","31"),
("Rye Malt Whiskey","Whiskey","Herbal-Spice","31"),
("Colorado Bourbon Whiskey","Bourbon","Woody-Nutty","31"),
("SNO Vodka","Vodka","Herbal-Spice","32"),
("FYR Liqueur","Liqueurs-Cordials","Herbal-Spice","32"),
("SNO Gin","Gin","None-Mild","32"),
("Jinn Ginn","Gin","None-Mild","33"),
("Ourye Whiskey","Whiskey","None-Mild","33"),
("Dead Drift Colorado Aged Whiskey","Whiskey","None-Mild","33"),
("Berthoud Blue Vodka","Vodka","None-Mild","33"),
("A.D. Laws Four Grain Straight Bourbon","Bourbon","Citrus","34"),
("A.D. Laws Four Grain Straight Bourbon Cask Strength","Bourbon","None-Mild","34"),
("A.D. Laws Farmers Select Single Barrel Four Grain Straight Bourbon","Bourbon","None-Mild","34"),
("A.D. Laws Four Grain Straight Bourbon Bottled in Bond","Bourbon","Fruity","34"),
("A.D. Laws Small Batch Secale Straight Rye","Whiskey","Herbal-Spice","34"),
("A.D. Laws Single Barrel Secale Straight Rye","Whiskey","None-Mild","34"),
("A.D. Laws Secale Straight Rye Bottled in Bond","Whiskey","Herbal-Spice","34"),
("A.D. Laws Hordeum Straight Malt Whiskey","Whiskey","Caramel","34"),
("A.D. Laws Triticum Straight Wheat Whiskey","Whiskey","Fruity","34"),
("A.D. Laws Straight Corn Whiskey Bottle Bond","Whiskey","None-Mild","34"),
("A.D. Laws Two Grain Straight Bourbon Bottled in Bond","Bourbon","None-Mild","34"),
("Lee Spirit Dry Gin","Gin","Floral","35"),
("Lee Spirit Lavender Gin","Gin","Floral","35"),
("Lee Spirit Strawberry Ginger Gin","Gin","Fruity","35"),
("Ginfuego","Gin","Herbal-Spice","35"),
("Forbidden Fruit","Liqueurs-Cordials","Citrus","35"),
("Creme de Violette","Liqueurs-Cordials","Herbal-Spice","35"),
("Creme de Cacao","Liqueurs-Cordials","Herbal-Spice","35"),
("Creme de Rose","Liqueurs-Cordials","Floral","35"),
("Alpine Liqueur","Liqueurs-Cordials","Herbal-Spice","35"),
("Peppermint Schnapps","Bitters-Schnapps","Herbal-Spice","35"),
("Winston Lee Blended Whiskey","Whiskey","None-Mild","35"),
("Leopold's Silver Tree Vodka","Vodka","None-Mild","36"),
("Leopold's American Small Batch Gin","Gin","Citrus","36"),
("Leopold's Summer Gin","Gin","Citrus","36"),
("Leopold's Navy Strength American Gin","Gin","None-Mild","36"),
("Leopold Bros. Straight Bourbon","Bourbon","Woody-Nutty","36"),
("American Small Batch Whiskey","Whiskey","Woody-Nutty","36"),
("Leopold Bros. Maryland-Style Rye Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. Michigan Cherry Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. Michigan Tart Cherry Liqueur","Liqueurs-Cordials","Fruity","36"),
("Leopold Bros. New York Apple Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. Rocky Mountain Blackberry Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. Rocky Mountain Blackberry Liqueur","Liqueurs-Cordials","Fruity","36"),
("Leopold Bros. Rocky Mountain Peach Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. Rocky Mountain Peach Liqueur","Liqueurs-Cordials","Fruity","36"),
("Leopold Bros. Georgia Peach Whiskey","Whiskey","Fruity","36"),
("Leopold Bros. American Orange Liqueur","Liqueurs-Cordials","Citrus","36"),
("Leopold Bros. Maraschino Liqueur","Liqueurs-Cordials","Fruity","36"),
("Leopold Bros. New England Cranberry Liqueur","Liqueurs-Cordials","Fruity","36"),
("Leopold Bros. Frenchpress-Style American Coffee Liqueur","Liqueurs-Cordials","None-Mild","36"),
("Leopold Bros. Three Pins Alpine Herbal Liqueur","Liqueurs-Cordials","Herbal-Spice","36"),
("Leopold Bros. Aperitivo","Other","Herbal-Spice","36"),
("Fernet Leopold Highland Amaro","Other","Herbal-Spice","36"),
("Leopold Bros. Absinthe Verte","Absinthe","Herbal-Spice","36"),
("Leopold Bros. New York Sour Apple Liqueur","Liqueurs-Cordials","Fruity","36"),
("Tiny's Oktoberfest Bierschnapps","Whiskey","Caramel","37"),
("The Last Waltz - Colorado Straight Bourbon Whiskey","Bourbon","Woody-Nutty","37"),
("Silver Pot - Distilled Light Rum","Rum","Caramel","37"),
("Shine - Locally Grown Corn Whiskey","Whiskey","None-Mild","37"),
("Fire - Cinnamon & Ginger Infused Whiskey","Whiskey","Herbal-Spice","37"),
("Gin","Gin","Woody-Nutty","37"),
("Lusca Spiced Rum","Rum","Herbal-Spice","37"),
("Amaro Arancia: Bitter Orange Liqueur","Liqueurs-Cordials","Citrus","37"),
("Bravo Zulu Bourbon Whiskey","Bourbon","None-Mild","38"),
("Bravo Zulu Delicious V.I Rum","Rum","Caramel","38"),
("Bravo Zulu Triple Filtered Vodka","Vodka","None-Mild","38"),
("Bravo Zulu Rocky Mountain Gin","Gin","None-Mild","38"),
("Marble Vodka","Vodka","None-Mild","39"),
("Marble Gingercello","Other","Herbal-Spice","39"),
("Marble Gingercello Reserve","Other","Herbal-Spice","39"),
("Marble Moonlight Expresso","Liqueurs-Cordials","Vanilla","39"),
("Hoover's Revenge, Ragged Mountain Rye","Whiskey","None-Mild","39"),
("Fireside Bourbon","Bourbon","Caramel","40"),
("Denver Dry Gin","Gin","Citrus","40"),
("Fireside Peach","Bourbon","Fruity","40"),
("Cuidadi Tequila","Tequila","Herbal-Spice","40"),
("Elevate Vodka","Vodka","None-Mild","40"),
("Peg-Leg Rum","Rum","None-Mild","40"),
("Mystic Mountain Outlaw Premim Whiskey","Whiskey","None-Mild","41"),
("Mystic Mountain Outlaw Red Premium Whiskey","Whiskey","Herbal-Spice","41"),
("Aces High Whiskey","Whiskey","Caramel","41"),
("Aces High Cinnamon Whiskey","Whiskey","Herbal-Spice","41"),
("Rocky Mountain Sippin' Hooch 101","Moonshine","None-Mild","41"),
("Orange Burst Mystic Mountain","Moonshine","Citrus","41"),
("Citrus Mystic Moonshine","Moonshine","Citrus","41"),
("Colorado Crystal Super Premium Vodka","Vodka","None-Mild","41"),
("Colorado Blue Vodka","Vodka","None-Mild","41"),
("Colorado Pig Gin","Gin","Herbal-Spice","41"),
("Hell Bear American Whiskey","Whiskey","Vanilla","42"),
("Chatter Wolf Vodka","Vodka","Caramel","42"),
("Needle Pig Gin","Gin","Floral","42"),
("Feather Jester Rum","Rum","Fruity","42"),
("Whiskey","Whiskey","None-Mild","43"),
("Gin","Gin","None-Mild","43"),
("Rum","Rum","None-Mild","43"),
("Infused Vodka","Vodka","None-Mild","43"),
("Botanical Vodka","Vodka","Herbal-Spice","43"),
("Brandy","Brandy","None-Mild","43"),
("Absinthe","Absinthe","None-Mild","43"),
("Blue Agave Spirits","Tequila","None-Mild","43"),
("Aquavit","Other","None-Mild","43"),
("Orange Liqueur","Liqueurs-Cordials","None-Mild","43"),
("Old Elk","Whiskey","Caramel","44"),
("Rabbit Bourbon Cream","Bourbon","Caramel","44"),
("Old Standard Organic Bourbon","Bourbon","Caramel","45"),
("Mountain Avenue Organic Gin","Gin","Floral","45"),
("Native Organic Vodka","Vodka","Caramel","45"),
("Old Standard Organic Rye Whiskey","Whiskey","Woody-Nutty","45"),
("Old Standard 'Moonshine' Small Batch Organic Whiskey","Whiskey","None-Mild","45"),
("Bourbon Whiskey","Bourbon","Vanilla","46"),
("Lavendar Gin","Gin","Herbal-Spice","46"),
("Vodka","Vodka","None-Mild","46"),
("Rasberry Vodka","Vodka","Fruity","46"),
("Spiced Rum","Rum","Herbal-Spice","46"),
("Blackberry Vodka","Vodka","Fruity","46"),
("Coffee","Liqueurs-Cordials","Vanilla","46"),
("Amaretto","Liqueurs-Cordials","Woody-Nutty","46"),
("Orange","Liqueurs-Cordials","Citrus","46"),
("Cinnamon","Liqueurs-Cordials","Herbal-Spice","46"),
("Jackelope & Jenny Gin","Gin","Woody-Nutty","47"),
("Jackelope & Jenny Aged Gin","Gin","None-Mild","47"),
("Jackelope Gin","Gin","Citrus","47"),
("Jackelope Aged Gin","Gin","Citrus","47"),
("Tub Gin","Gin","None-Mild","47"),
("Colorado Staright Bourbon","Bourbon","None-Mild","47"),
("American Single Malt Whiskey","Whiskey","Woody-Nutty","47"),
("Smoked Rye Whiskey","Whiskey","Woody-Nutty","47"),
("Coat Artisan Vodka","Vodka","None-Mild","47"),
("Pear Brandy","Brandy","Fruity","47"),
("Peach Brandy","Brandy","Fruity","47"),
("Apricot Brandy","Brandy","Fruity","47"),
("Peach Brandy Eau De Vie","Brandy","Fruity","47"),
("Plum Brandy Eau De Vie","Brandy","Fruity","47"),
("Pear Brandy Eau De Vie","Brandy","Fruity","47"),
("Cherry Brandy Eau De Vie","Brandy","Fruity","47"),
("Apricot Brandy Eau De Vie","Brandy","Fruity","47"),
("D'Agave Silver","Tequila","None-Mild","47"),
("D'Agave Gold","Tequila","Woody-Nutty","47"),
("D'Agave Extra","Tequila","None-Mild","47"),
("Grappa of Gewurztraminer","Other","Herbal-Spice","47"),
("Grappa of Viognier","Other","Fruity","47"),
("Grappa Muscat","Other","None-Mild","47"),
("Bier Schnapps - Lefthand IPA","Bitters-Schnapps","None-Mild","47"),
("Bier Schnapps - Steeltoe Stout","Bitters-Schnapps","Vanilla","47"),
("Amaro Liqueur","Liqueurs-Cordials","Herbal-Spice","47"),
("RSD Organic Bourbon","Bourbon","Woody-Nutty","48"),
("RSD Organic Rye Whiskey","Whiskey","Herbal-Spice","48"),
("RSD Organic Vodka","Vodka","None-Mild","48"),
("RSD Silk Road Organic Gin","Gin","Herbal-Spice","48"),
("RSD Organic Oaked Silk Road Gin","Gin","Vanilla","48"),
("RSD Lavendar Hibiscus Liqueur","Liqueurs-Cordials","Herbal-Spice","48"),
("RSD Colorado Chile Liqueur","Liqueurs-Cordials","Herbal-Spice","48"),
("RSD Colorado Chile Whiskey","Whiskey","Herbal-Spice","48"),
("RSD Colorado Peach Brandy","Brandy","Fruity","48"),
("RSD Organic Coffee Liqueur","Liqueurs-Cordials","Herbal-Spice","48"),
("Rocker Whiskey","Whiskey","Caramel","49"),
("Rocker Rum","Rum","Caramel","49"),
("Rocker Vodka","Vodka","None-Mild","49"),
("Sand Creek Single Malt Whiskey","Whiskey","Woody-Nutty","50"),
("Silver Coyote Pure Malt Whiskey","Whiskey","Caramel","51"),
("Expedition Vodka","Vodka","None-Mild","51"),
("Santa Fe Spirits Apple Brandy","Brandy","Fruity","51"),
("Wheeler's Gin","Gin","Floral","51"),
("Colkegan Single Malt Whiskey","Whiskey","Woody-Nutty","51"),
("Atapino Liqueur","Liqueurs-Cordials","Woody-Nutty","51"),
("Slow Burn","Gin","Woody-Nutty","51"),
("Colkegan Apple Brandy Cask Finished","Brandy","Fruity","51"),
("Colkegan Cask Strength Single Malt Whiskey","Whiskey","Woody-Nutty","51"),
("Spirit Hound Straight Malt Whiskey","Whiskey","Woody-Nutty","52"),
("Spirit Hound Gin","Gin","Herbal-Spice","52"),
("Spirit Hound Montain Bum Rum","Rum","Caramel","52"),
("Spirit Hound Colorado Sambuca","Other","Herbal-Spice","52"),
("Spirit Hound White Dog Moonshine","Moonshine","None-Mild","52"),
("The Clever Jack - Blanco Agave","Tequila","None-Mild","53"),
("The Young Ace - Agave Reposado","Tequila","Woody-Nutty","53"),
("The Wise King - Anejo Agave","Tequila","Woody-Nutty","53"),
("The Pious Queen","Vodka","None-Mild","53"),
("The Astute Jester","Gin","Herbal-Spice","53"),
("Colorado Bourbon Whiskey","Bourbon","Caramel","53"),
("Scottish Peat Smoked Whiskey","Whiskey","Woody-Nutty","53"),
("Darling Apple Brandy","Brandy","Fruity","53"),
("Warrior Whiskey","Whiskey","None-Mild","54"),
("Colorado Silver","Other","None-Mild","55"),
("Barrel Reserve","Other","None-Mild","55"),
("Cin.Fire","Other","Herbal-Spice","55"),
("Lucky-Oh","Other","None-Mild","55"),
("176 Proof","Other","None-Mild","55"),
("Stranahan's Original","Whiskey","Caramel","57"),
("Stranahan's Diamond Peak","Whiskey","Fruity","57"),
("Stranahan's Sherry Cask","Other","Caramel","57"),
("Stranahan's SnowFlake","Whiskey","None-Mild","57"),
("Stranahan's Single Barrel","Whiskey","None-Mild","57"),
("Straight Bourbon Whiskey","Bourbon","Caramel","58"),
("Crystal Vodka","Vodka","None-Mild","58"),
("Rose Gin","Gin","Floral","58"),
("Heavy Rum","Rum","Vanilla","58"),
("Wellhead Whiskey","Whiskey","None-Mild","58"),
("CarrowDair Whiskey","Whiskey","Woody-Nutty","59"),
("Inishan Whiskey","Whiskey","Herbal-Spice","59"),
("Finglas Dubdair Gin","Gin","Herbal-Spice","59"),
("Finglas Fin","Gin","Citrus","59"),
("Summer Gin","Gin","Citrus","60"),
("Autumn Gin","Gin","Herbal-Spice","60"),
("Vodka","Vodka","None-Mild","60"),
("StopGap Jones Rye Whiskey","Whiskey","None-Mild","61"),
("Juniper Jones Gin","Gin","None-Mild","61"),
("StopGap Jones Bourbon","Bourbon","None-Mild","61"),
("Annika Jones Vodka","Vodka","None-Mild","61"),
("Mo Jones Rum","Rum","None-Mild","61"),
("The Heart Gin","Gin","Herbal-Spice","62"),
("Colorado Straight Bourbon Whiskey","Bourbon","Caramel","62"),
("The Heart Vodka","Vodka","None-Mild","62"),
("Trinity Absinthe","Absinthe","Herbal-Spice","62"),
("Colorado Straight Rye Whiskey","Whiskey","Caramel","62"),
("Tower 56 Bourbon","Bourbon","Woody-Nutty","63"),
("Tower 56 Gin","Gin","Citrus","63"),
("Tower 56 Vodka","Vodka","None-Mild","63"),
("Tower 56 Almondretto","Liqueurs-Cordials","Woody-Nutty","63"),
("Tower 56 Coffee Spirit","Liqueurs-Cordials","Caramel","63"),
("Tower 56 Cask 56","Gin","Citrus","63"),
("Boulder American Single Malt Whiskey - American Oak","Whiskey","Fruity","64"),
("Boulder American Single Malt Whiskey - Peated","Whiskey","Woody-Nutty","64"),
("Boulder American Single Malt Whiskey - Port Cask","Whiskey","Fruity","64"),
("Boulder Bourbon","Bourbon","Fruity","64"),
("Boulder Vodka","Vodka","None-Mild","64"),
("Boulder Gin","Gin","Herbal-Spice","64"),
("Boulder Pink Gin","Gin","Citrus","64"),
("Boulder Ginskey, Barrel Aged Gin","Gin","Caramel","64"),
("Pumpkin King Cordial","Liqueurs-Cordials","Herbal-Spice","64"),
("Arrosta","Other","Vanilla","64"),
("Boulder Navy Strength Gin","Gin","Floral","64"),
("Blue Corn Vodka","Vodka","None-Mild","65"),
("Founder's Rye Whiskey","Whiskey","None-Mild","65"),
("Wine Barrel Aged Rum","Rum","None-Mild","65"),
("Amber Rum","Rum","Caramel","65"),
("White Rum","Rum","Caramel","65"),
("Sawatch American Malt Whiskey","Whiskey","Woody-Nutty","66"),
("Tenderfool Malt Whiskey","Whiskey","Herbal-Spice","66"),
("Alpine Rye Whiskey","Whiskey","Herbal-Spice","66"),
("Treeline Gin","Gin","Woody-Nutty","66"),
("Treeline Barrel Rested Gin","Gin","Vanilla","66"),
("Mountain Hopped Gin","Gin","Floral","66"),
("Fleur de Sureau - Elderflower Liqueur","Liqueurs-Cordials","Floral","66"),
("Reserve Vodka","Vodka","None-Mild","67"),
("100% Potato Vodka","Vodka","None-Mild","67"),
("Straight Rye","Whiskey","Herbal-Spice","67"),
("Colorado Gin","Gin","Herbal-Spice","67");